GET https://expences-app-essi.onrender.com/api/expenses/

###

GET https://expences-app-essi.onrender.com/api/expenses/filter?shop=prisma

###
GET https://expences-app-essi.onrender.com/api/expenses/2022/12

###
POST https://expences-app-essi.onrender.com/api/expenses/ HTTP/1.1
content-type: application/json

{
  "date": "2023-01-14",
  "amount": "8.99",
  "category": "viini",
  "shop": "alko"
}
###
DELETE https://expences-app-essi.onrender.com/api/expenses/5
###

PUT https://expences-app-essi.onrender.com/api/expenses/ HTTP/1.1
content-type: application/json

{
  "id": 6,
  "date": "2023-01-14",
  "amount": "1.88",
  "category": "ruoka",
  "shop": "sale"
}

