GET http://localhost:5000/api/expenses/

### vaihda RENDEROSOITTEET

GET http://localhost:5000/api/expenses/filter?amount=80

###
GET http://localhost:5000/api/expenses/2022/12

###
POST http://localhost:5000/api/expenses HTTP/1.1
content-type: application/json

{
  "date": "2022-12-24",
  "amount": "2.55",
  "category": "ruoka",
  "shop": "sale"
}
###
DELETE http://localhost:5000/api/expenses/5
###

PUT http://localhost:5000/api/expenses HTTP/1.1
content-type: application/json

{
  "id": 6,
  "date": "2023-01-14",
  "amount": "1.88",
  "category": "ruoka",
  "shop": "sale"
}

